apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: app-tomcat
spec:
  selector:
    app: app-tomcat
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
